/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vue;

import Modele.Adresse;
import Modele.Employe;
import Modele.Users;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Fenêtre d'ajout / modification d'un Employé + User + Adresse
 */
public class FenetreAjoutUtilisateur extends javax.swing.JDialog {
    private GestionUtilisateurs parent;

    // null => mode ajout, != null => mode modification
    private Integer idEmploye = null;
    private Integer idUser = null; // si vous devez modifier l'utilisateur existant
    private Integer idAdresse = null; // s'il vous faut gérer l'adresse

    /**
     * Constructeur pour AJOUT (aucun employé existant).
     */
    public FenetreAjoutUtilisateur(GestionUtilisateurs parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
        this.setTitle("Ajouter un Employé");
    }

    /**
     * Constructeur pour MODIFICATION.
     * On reçoit les objets existants pour pré-remplir le formulaire.
     */
    public FenetreAjoutUtilisateur(GestionUtilisateurs parent, boolean modal, 
        Employe emp, Adresse adr, Users user) {
        super(parent, modal);
        this.parent = parent;

        // On sait qu'on est en mode "Modification" => on stocke les IDs
        this.idEmploye = emp.getIdEmploye();
        this.idUser = emp.getIdUser(); // ou user.getIdUser()
        this.idAdresse = emp.getIdAdresse(); // s'il y a un champ idAdresse dans l'employé

        initComponents();
        this.setTitle("Modifier un Employé");

        // Pré-remplir avec les infos de l'employé
        jTextF_Nom.setText(emp.getNom());
        jTextF_Prenom.setText(emp.getPrenom());
        jTextF_Titre.setText(emp.getTitre());
        jTextF_Salaire.setText(String.valueOf(emp.getSalaire()));
        jTextF_PCommi.setText(String.valueOf(emp.getPctCommission()));

        // Pré-remplir l'adresse
        if (adr != null) {
            jTextF_Numrue.setText(String.valueOf(adr.getNumRue()));
            jTextF_Nomrue.setText(adr.getNomRue());
            jTextF_Localite.setText(adr.getLocalite());
            jTextF_Pays.setText(adr.getPays());
            jTextF_CodePostal.setText(adr.getCodePostal());
        }

        // Pré-remplir l'utilisateur
        if (user != null) {
            jTextF_Username.setText(user.getUsername());
            // On n’affiche pas le password existant
            // On set la comboBox du rôle
            jComboBox_Role.setSelectedIndex(user.getIdPrivilege() - 1); 
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLab_Nom = new javax.swing.JLabel();
        jLab_Prenom = new javax.swing.JLabel();
        jLab_Titre = new javax.swing.JLabel();
        jLab_Salaire = new javax.swing.JLabel();
        jLab_PCommi = new javax.swing.JLabel();
        jLab_Numrue = new javax.swing.JLabel();
        jLab_Nomrue = new javax.swing.JLabel();
        jLab_Localite = new javax.swing.JLabel();
        jLab_Pays = new javax.swing.JLabel();
        jLab_Codepostal = new javax.swing.JLabel();
        jLab_Username = new javax.swing.JLabel();
        jLab_Password = new javax.swing.JLabel();
        jComboBox_Role = new javax.swing.JComboBox<>();
        jTextF_Nom = new javax.swing.JTextField();
        jTextF_Titre = new javax.swing.JTextField();
        jTextF_PCommi = new javax.swing.JTextField();
        jTextF_Numrue = new javax.swing.JTextField();
        jTextF_Nomrue = new javax.swing.JTextField();
        jTextF_CodePostal = new javax.swing.JTextField();
        jTextF_Prenom = new javax.swing.JTextField();
        jTextF_Salaire = new javax.swing.JTextField();
        jTextF_Localite = new javax.swing.JTextField();
        jTextF_Pays = new javax.swing.JTextField();
        jTextF_Username = new javax.swing.JTextField();
        jBtn_Valider = new javax.swing.JButton();
        jPasswordF_Password = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLab_GrandTitre = new javax.swing.JLabel();
        jBtn_Annuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLab_Nom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLab_Nom.setText("Nom");
        getContentPane().add(jLab_Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 100, -1, -1));

        jLab_Prenom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLab_Prenom.setText("Prenom");
        getContentPane().add(jLab_Prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        jLab_Titre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLab_Titre.setText("Titre");
        getContentPane().add(jLab_Titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 166, -1, -1));

        jLab_Salaire.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLab_Salaire.setText("Salaire");
        getContentPane().add(jLab_Salaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLab_PCommi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLab_PCommi.setText("pct_commission");
        getContentPane().add(jLab_PCommi, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 236, -1, -1));

        jLab_Numrue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLab_Numrue.setText("Num_rue");
        getContentPane().add(jLab_Numrue, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 288, -1, -1));

        jLab_Nomrue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLab_Nomrue.setText("Nom_rue");
        getContentPane().add(jLab_Nomrue, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 349, -1, -1));

        jLab_Localite.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLab_Localite.setText("Localite");
        getContentPane().add(jLab_Localite, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        jLab_Pays.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLab_Pays.setText("Pays");
        getContentPane().add(jLab_Pays, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, -1, -1));

        jLab_Codepostal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLab_Codepostal.setText("Code_postal");
        getContentPane().add(jLab_Codepostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 388, -1, -1));

        jLab_Username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLab_Username.setText("Username");
        getContentPane().add(jLab_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        jLab_Password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLab_Password.setText("Password");
        getContentPane().add(jLab_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, -1, -1));

        jComboBox_Role.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox_Role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Gerant", "Utilisateur", " " }));
        getContentPane().add(jComboBox_Role, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        jTextF_Nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextF_NomActionPerformed(evt);
            }
        });
        getContentPane().add(jTextF_Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 213, -1));
        getContentPane().add(jTextF_Titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 166, 213, -1));
        getContentPane().add(jTextF_PCommi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 236, 213, -1));
        getContentPane().add(jTextF_Numrue, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 288, 213, -1));
        getContentPane().add(jTextF_Nomrue, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 349, 213, -1));
        getContentPane().add(jTextF_CodePostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 210, -1));
        getContentPane().add(jTextF_Prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 210, -1));
        getContentPane().add(jTextF_Salaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 210, -1));
        getContentPane().add(jTextF_Localite, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 210, -1));
        getContentPane().add(jTextF_Pays, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 210, -1));
        getContentPane().add(jTextF_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 210, -1));

        jBtn_Valider.setBackground(new java.awt.Color(204, 255, 204));
        jBtn_Valider.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtn_Valider.setText("Valider");
        jBtn_Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ValiderActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn_Valider, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, -1, -1));
        getContentPane().add(jPasswordF_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 210, -1));

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLab_GrandTitre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLab_GrandTitre.setText("FenetreAjoutUtilisateur");
        jPanel1.add(jLab_GrandTitre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jBtn_Annuler.setBackground(new java.awt.Color(204, 255, 204));
        jBtn_Annuler.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtn_Annuler.setText("Annuler");
        jBtn_Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_AnnulerActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn_Annuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ValiderActionPerformed
            try {
        // 1) Récupérer infos saisies
        String nom = jTextF_Nom.getText().trim();
        String prenom = jTextF_Prenom.getText().trim();
        String titre = jTextF_Titre.getText().trim();
        double salaire = Double.parseDouble(jTextF_Salaire.getText());
        double pctCom = Double.parseDouble(jTextF_PCommi.getText());

        int numRue = Integer.parseInt(jTextF_Numrue.getText().trim());
        String nomRue = jTextF_Nomrue.getText().trim();
        String localite = jTextF_Localite.getText().trim();
        String pays = jTextF_Pays.getText().trim();
        String codePostal = jTextF_CodePostal.getText().trim();

        String username = jTextF_Username.getText().trim();
        String password = new String(jPasswordF_Password.getPassword());
        int idPrivilege = jComboBox_Role.getSelectedIndex() + 1;

        // Vérification basique des champs
        if (nom.isEmpty() || prenom.isEmpty() || titre.isEmpty()
                || username.isEmpty() || password.isEmpty()
                || nomRue.isEmpty() || localite.isEmpty() || pays.isEmpty()
                || codePostal.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "❗ Tous les champs doivent être remplis.",
                    "Erreur",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // === Vérifier si on est en mode AJOUT ou MODIFICATION
        if (idEmploye == null) {
            // --- Mode AJOUT ---

            // 1) Créer l'adresse en BD
            Adresse adr = new Adresse(numRue, nomRue, localite, pays, codePostal);
            Adresse.createAdresse(adr); // <-- insère l'adresse et met son id_adresse

            // 2) Créer l'utilisateur en BD et RÉCUPÉRER l'id_user
            //    On utilise une méthode qui renvoie un int
            int newUserId = Users.ajouterUtilisateur(username, password, "actif",idPrivilege);
            if (newUserId <= 0) {
                JOptionPane.showMessageDialog(this, "Erreur lors de la création de l'utilisateur !");
                return; // on arrête, pas d'utilisateur => pas d'employé
            }

            // 3) Créer l'employé
            Employe e = new Employe();
            e.setNom(nom);
            e.setPrenom(prenom);
            e.setTitre(titre);
            e.setSalaire(salaire);
            e.setPctCommission(pctCom);

            e.setIdAdresse(adr.getIdAdresse()); // on lie l'adresse
            e.setIdUser(newUserId);             // on lie l'utilisateur (FK)

            boolean ok = Employe.createEmploye(e);
            if (ok) {
                JOptionPane.showMessageDialog(this, "Employé ajouté avec succès !");
                if (parent != null) {
                    parent.loadUsers();
                    parent.loadEmployes();
                }
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Erreur lors de l'ajout !");
            }

        } else {
            // --- Mode MODIFICATION ---

            // 1) Charger l'employé depuis la BD
            Employe e = Employe.getEmployeById(idEmploye);
            if (e == null) {
                JOptionPane.showMessageDialog(this, "Employé introuvable.");
                return;
            }

            // 2) Charger (ou créer) l'adresse
            Adresse adr = Adresse.getAdresseById(e.getIdAdresse());
            if (adr == null) {
                // Pas d'adresse => en créer une
                adr = new Adresse(numRue, nomRue, localite, pays, codePostal);
                Adresse.createAdresse(adr);
                e.setIdAdresse(adr.getIdAdresse());
            } else {
                // Mettre à jour l'adresse
                adr.setNumRue(numRue);
                adr.setNomRue(nomRue);
                adr.setLocalite(localite);
                adr.setPays(pays);
                adr.setCodePostal(codePostal);
                Adresse.updateAdresse(adr);
            }

            // 3) Mettre à jour l'employé
            e.setNom(nom);
            e.setPrenom(prenom);
            e.setTitre(titre);
            e.setSalaire(salaire);
            e.setPctCommission(pctCom);

            // 4) Mettre à jour le user
            Users u = Users.getUserById(e.getIdUser());
            if (u != null) {
                u.setUsername(username);

                // si password pas vide => on modifie
                if (!password.isEmpty()) {
                    u.setMotDePasse(password);
                }
                u.setIdPrivilege(idPrivilege);

                // updateUser(...) : si la signature est (int idUser, String username, String mdp, int priv)
                Users.updateUser(u.getIdUser(), u.getUsername(), u.getMotDePasse(),u.getStatut(), u.getIdPrivilege());
            }

            // 5) Update de l'employé
            boolean ok = Employe.updateEmploye(e);
            if (ok) {
                JOptionPane.showMessageDialog(this, "Employé modifié avec succès !");
                if (parent != null) {
                    parent.loadUsers();
                    parent.loadEmployes();
                }
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Erreur lors de la modification !");
            }
        }

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Format numérique invalide.");
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur SQL: " + ex.getMessage());
    } catch (ClassNotFoundException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur DB: " + ex.getMessage());
    }
    

    }//GEN-LAST:event_jBtn_ValiderActionPerformed

    private void jBtn_AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_AnnulerActionPerformed
        // TODO add your handling code here:
        dispose(); // Ferme la fenêtre
    }//GEN-LAST:event_jBtn_AnnulerActionPerformed

    private void jTextF_NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextF_NomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextF_NomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreAjoutUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreAjoutUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreAjoutUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreAjoutUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FenetreAjoutUtilisateur dialog = new FenetreAjoutUtilisateur((GestionUtilisateurs) new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Annuler;
    private javax.swing.JButton jBtn_Valider;
    private javax.swing.JComboBox<String> jComboBox_Role;
    private javax.swing.JLabel jLab_Codepostal;
    private javax.swing.JLabel jLab_GrandTitre;
    private javax.swing.JLabel jLab_Localite;
    private javax.swing.JLabel jLab_Nom;
    private javax.swing.JLabel jLab_Nomrue;
    private javax.swing.JLabel jLab_Numrue;
    private javax.swing.JLabel jLab_PCommi;
    private javax.swing.JLabel jLab_Password;
    private javax.swing.JLabel jLab_Pays;
    private javax.swing.JLabel jLab_Prenom;
    private javax.swing.JLabel jLab_Salaire;
    private javax.swing.JLabel jLab_Titre;
    private javax.swing.JLabel jLab_Username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordF_Password;
    private javax.swing.JTextField jTextF_CodePostal;
    private javax.swing.JTextField jTextF_Localite;
    private javax.swing.JTextField jTextF_Nom;
    private javax.swing.JTextField jTextF_Nomrue;
    private javax.swing.JTextField jTextF_Numrue;
    private javax.swing.JTextField jTextF_PCommi;
    private javax.swing.JTextField jTextF_Pays;
    private javax.swing.JTextField jTextF_Prenom;
    private javax.swing.JTextField jTextF_Salaire;
    private javax.swing.JTextField jTextF_Titre;
    private javax.swing.JTextField jTextF_Username;
    // End of variables declaration//GEN-END:variables
}
