/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;


//import javax.swing.ImageIcon;
import Controle.Configuration;
import  java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import Controle.ControleConnexion;
import Modele.Employe;
import Modele.Users;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author Win10_ET
 */
public class FenetreConnexion extends javax.swing.JFrame {
    private boolean mdpVisible = false; // Variable d'instance pour suivre l'état du mot de passe
    public static Employe employeActif = null; // Variable statique accessible depuis tout le projet
    
    /**
     * Creates new form FenetreConnexion
     */
    public FenetreConnexion() throws SQLException, ClassNotFoundException {
        Users.updatePasswordsToBCrypt(); // 🔄 Mise à jour au lancement
        initComponents();
        complementGUI();
        // Initialiser les champs de texte vides
        jText_Nom.setText(""); 
        jPasF_Password.setText(""); 
    }
    
    private void complementGUI() {
        Image       im = Toolkit.getDefaultToolkit().getImage("..\\Projet_Expl_P1\\src\\Images\\logo.png");
        //ImageIcon     im2 = new ImageIcon("C:\\Users\\Win10_ET\\Desktop\\Projet Expl 2019-2020\\Projet_P1\\Projet_Expl_P1\\src\\Images\\logo.png");
        
        setIconImage(im);
        //setIconImage(im2.getImage());
        setTitle("Programme Expl P1");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jText_Nom = new javax.swing.JTextField("root");
        jPasF_Password = new javax.swing.JPasswordField("test");
        jBtn_Valider = new javax.swing.JButton();
        jLab_MDP = new javax.swing.JLabel();
        jLab_Nom = new javax.swing.JLabel();
        jBtn_Annuler = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        Stock_manager = new javax.swing.JLabel();
        jBtn_Quitter = new javax.swing.JButton();
        jBtn_VoirMdp = new javax.swing.JButton();
        jLab_MiniFond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jText_Nom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jText_Nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_NomActionPerformed(evt);
            }
        });
        getContentPane().add(jText_Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 240, 40));

        jPasF_Password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jPasF_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 240, 40));

        jBtn_Valider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/valider.png"))); // NOI18N
        jBtn_Valider.setText("Valider");
        jBtn_Valider.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jBtn_Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ValiderActionPerformed(evt);
            }
        });
        jBtn_Valider.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtn_ValiderKeyPressed(evt);
            }
        });
        getContentPane().add(jBtn_Valider, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 240, 40));

        jLab_MDP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLab_MDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/password.png"))); // NOI18N
        jLab_MDP.setText("Mot de passe");
        getContentPane().add(jLab_MDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 130, 40));

        jLab_Nom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLab_Nom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/login.JPG"))); // NOI18N
        jLab_Nom.setText("Nom");
        getContentPane().add(jLab_Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 130, 30));

        jBtn_Annuler.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtn_Annuler.setText("Annuler");
        jBtn_Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_AnnulerActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn_Annuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 100, 30));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField1.setText("Connexion au programme");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 300, 40));

        Stock_manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/Gestion Stock.png"))); // NOI18N
        getContentPane().add(Stock_manager, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 60, -1));

        jBtn_Quitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/quitter.JPG"))); // NOI18N
        jBtn_Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_QuitterActionPerformed(evt);
            }
        });
        jBtn_Quitter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtn_QuitterKeyPressed(evt);
            }
        });
        getContentPane().add(jBtn_Quitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, -1));

        jBtn_VoirMdp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtn_VoirMdp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/voirMDP.JPG"))); // NOI18N
        jBtn_VoirMdp.setText("VoirMdp");
        jBtn_VoirMdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_VoirMdpActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn_VoirMdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, -1, -1));

        jLab_MiniFond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/ban.png"))); // NOI18N
        getContentPane().add(jLab_MiniFond, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 430));

        setSize(new java.awt.Dimension(764, 523));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ValiderActionPerformed
            
            String username = jText_Nom.getText();
            String password = new String(jPasF_Password.getPassword());

            if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez entrer un nom d'utilisateur et un mot de passe.", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Récupérer l'utilisateur via son username
            Users user = Users.authenticate(username,password);

            if (user != null) {
                System.out.println("✅ Utilisateur trouvé : " + user.getUsername());

                // Vérifier si le mot de passe correspond
                if (user.verifyPassword(password)) {
                    JOptionPane.showMessageDialog(this, "Connexion réussie, bienvenue " + user.getUsername() + " !");
                    
                    // 3) Récupérer l’employé associé
                    Employe emp = Employe.getEmployeByUserId(user.getIdUser());
                    if (emp == null) {
                        JOptionPane.showMessageDialog(this, "Aucun employé associé à cet utilisateur");
                        return;
                    }

                    // 4) Stocker la référence dans la variable statique
                    employeActif = emp;
                    

                    // Redirection après connexion
                    FenetrePrincipale fenetrePrincipale = new FenetrePrincipale(user.getIdPrivilege());
                    fenetrePrincipale.setVisible(true);

                    this.dispose(); // Fermer la fenêtre de connexion
                } else {
                    JOptionPane.showMessageDialog(this, "Mot de passe incorrect.", "Erreur", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Utilisateur non trouvé.", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur de connexion : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }//GEN-LAST:event_jBtn_ValiderActionPerformed

    private void jBtn_ValiderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtn_ValiderKeyPressed
        
    }//GEN-LAST:event_jBtn_ValiderKeyPressed

    private void jBtn_AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_AnnulerActionPerformed
        // TODO add your handling code here:
        jText_Nom.setText(""); 
        jPasF_Password.setText("");
    }//GEN-LAST:event_jBtn_AnnulerActionPerformed

    private void jText_NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_NomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_NomActionPerformed

    private void jBtn_QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_QuitterActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBtn_QuitterActionPerformed

    private void jBtn_QuitterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtn_QuitterKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
             System.exit(0);
            
        }
    }//GEN-LAST:event_jBtn_QuitterKeyPressed
  
    private void jBtn_VoirMdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_VoirMdpActionPerformed
        // TODO add your handling code here:
        //boolean mdpVisible = false; // Variable pour suivre l'état du mot de passe
        if (mdpVisible) {
            // Masquer le mot de passe
            jPasF_Password.setEchoChar('*'); // Remplace par un caractère de masquage
            mdpVisible = false;
            jBtn_VoirMdp.setText("Voir Mdp"); // Optionnel : changer le texte du bouton
        } else {
            // Afficher le mot de passe
            jPasF_Password.setEchoChar((char) 0); // Aucun caractère de masquage
            mdpVisible = true;
            jBtn_VoirMdp.setText("Masquer Mdp"); // Optionnel : changer le texte du bouton
        }
    }//GEN-LAST:event_jBtn_VoirMdpActionPerformed
    
    private boolean controleConnexion_Appel() {
    // Récupération des saisies utilisateur
    String leNom = jText_Nom.getText(); // Récupération du texte saisi dans le champ "Nom"
    String leMotDePasse = String.valueOf(jPasF_Password.getPassword()); // Récupération du mot de passe saisi

    boolean bControle = false;

    // Vérification des données via le contrôleur (exemple avec ControleConnexionSingleton)
    if (ControleConnexion.controle(leNom, leMotDePasse)) {
        if (ControleConnexion.isEtatConnexion()) {
            bControle = true;
        } else {
            JOptionPane.showMessageDialog(null,
                    "Impossible de se connecter"
                    + " à la base de données.\n\n"
                    + "Vos nom et mot de passe sont corrects.\n"
                    + "Mais les paramètres pour le pilote"
                    + " et la base de données "
                    + "doivent être vérifiés.\n\n"
                    + "Contacter le responsable informatique.",
                    "ALERTE", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, 
                "Nom d'utilisateur ou mot de passe incorrect.",
                "Erreur de connexion", 
                JOptionPane.ERROR_MESSAGE);
    }
    return bControle;
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        try {
        // 1) Charger depuis le .properties en clair
        //    (car on a supprimé .enc, il ne le trouvera pas)
            Configuration.loadProperties();
 
        // 2) Vérifier que les propriétés sont bonnes
            System.out.println("Avant chiffrement, driver = " + Configuration.getProperty("db.driver"));
 
        // 3) Appeler réellement saveProperties() pour produire config.enc
           Configuration.saveAndEncryptProperties();

            System.out.println("Fichier .enc généré réellement !");
 
        // 4) Relancer un loadProperties() pour voir si .enc est bien relu
            Configuration.loadProperties();
            System.out.println("Après recharge .enc, driver = " + Configuration.getProperty("db.driver"));
            ControleConnexion.transfertDonnees();
 
        } catch (Exception e) {
        e.printStackTrace();
        }
 
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FenetreConnexion().setVisible(true);
                    
                    /*if(ControleConnexionSingleton.isEtatConnexion())*/
                    /*else JOptionPane.showMessageDialog(null,
                    "Impossible de se connecter"
                    + " à la base de données.\n\n"
                    + "Les paramètres pour le pilote"
                    + " et de la base de données "
                    + "doivent être vérifiés.\n\n"
                    + "Contacter le responsable informatique.",
                    "ALERTE", JOptionPane.ERROR_MESSAGE);*/
                } catch (SQLException ex) {
                    Logger.getLogger(FenetreConnexion.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FenetreConnexion.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Stock_manager;
    private javax.swing.JButton jBtn_Annuler;
    private javax.swing.JButton jBtn_Quitter;
    private javax.swing.JButton jBtn_Valider;
    private javax.swing.JButton jBtn_VoirMdp;
    private javax.swing.JLabel jLab_MDP;
    private javax.swing.JLabel jLab_MiniFond;
    private javax.swing.JLabel jLab_Nom;
    private javax.swing.JPasswordField jPasF_Password;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jText_Nom;
    // End of variables declaration//GEN-END:variables

    
}
