/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vue;

import Controle.Configuration;
import Modele.Employe;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class FenetrePrincipale extends javax.swing.JFrame {
    private int idPrivilege; // Pour stocker le rôle de l'utilisateur
    /**
     * Creates new form FenetrePrincipale
     */
    public FenetrePrincipale() {
        initComponents();
    }
    
    public FenetrePrincipale(int idPrivilege) {
        initComponents();
        this.idPrivilege = idPrivilege;
        gererAccesMenus(); // Appliquer les restrictions
    }

    private void gererAccesMenus() {
        if (idPrivilege >= 3) { // Si ce n'est NI un Admin (1) NI un Gérant (2)
            jMenuItem_GestionUtili.setVisible(false); // Rendre l'option invisible
            jMenuItem_GestionPara.setVisible(false); // Rendre l'option invisible
        }
        if (idPrivilege != 1){ //Si ce n'est pas un Admin (1)
            jMenuItem_GestionPara.setVisible(false); // Rendre l'option invisible
            //jMenuItem_GestionUtili.setVisible(false); // Rendre l'option invisible
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtn_Quitter = new javax.swing.JButton();
        jBtn_Deconnecter = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1_Fenetre = new javax.swing.JMenu();
        jMenuItem_GestionClt = new javax.swing.JMenuItem();
        jMenuItem_GestionUtili = new javax.swing.JMenuItem();
        jMenuItem_GestionPara = new javax.swing.JMenuItem();
        jMenuItem_Gestion_stock = new javax.swing.JMenuItem();
        jMenuItem_GestionVente = new javax.swing.JMenuItem();
        jMenu2_Edition = new javax.swing.JMenu();
        jMenuItem_Copier = new javax.swing.JMenuItem();
        jMenuItem_Coller = new javax.swing.JMenuItem();
        jMenuItem_Couper = new javax.swing.JMenuItem();
        jMenu3_Aide = new javax.swing.JMenu();
        jMenuItem_Apropos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtn_Quitter.setBackground(new java.awt.Color(204, 204, 204));
        jBtn_Quitter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtn_Quitter.setForeground(new java.awt.Color(0, 153, 51));
        jBtn_Quitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/quitter.png"))); // NOI18N
        jBtn_Quitter.setText("Quitter");
        jBtn_Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_QuitterActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn_Quitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, -1));

        jBtn_Deconnecter.setBackground(new java.awt.Color(204, 204, 204));
        jBtn_Deconnecter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtn_Deconnecter.setForeground(new java.awt.Color(0, 153, 51));
        jBtn_Deconnecter.setText("Se Deconnecter");
        jBtn_Deconnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DeconnecterActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn_Deconnecter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/image_fond.JPG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 700, 390));

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 700, 410));

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));
        jMenuBar1.setForeground(new java.awt.Color(51, 153, 0));

        jMenu1_Fenetre.setText("Fenêtres");
        jMenu1_Fenetre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem_GestionClt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem_GestionClt.setText("GestionClients");
        jMenuItem_GestionClt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_GestionCltActionPerformed(evt);
            }
        });
        jMenu1_Fenetre.add(jMenuItem_GestionClt);

        jMenuItem_GestionUtili.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem_GestionUtili.setText("Gestion_Utilisateurs");
        jMenuItem_GestionUtili.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_GestionUtiliActionPerformed(evt);
            }
        });
        jMenu1_Fenetre.add(jMenuItem_GestionUtili);

        jMenuItem_GestionPara.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem_GestionPara.setText("Gestion des parametres");
        jMenuItem_GestionPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_GestionParaActionPerformed(evt);
            }
        });
        jMenu1_Fenetre.add(jMenuItem_GestionPara);

        jMenuItem_Gestion_stock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem_Gestion_stock.setText("Gestion_stock");
        jMenuItem_Gestion_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Gestion_stockActionPerformed(evt);
            }
        });
        jMenu1_Fenetre.add(jMenuItem_Gestion_stock);

        jMenuItem_GestionVente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem_GestionVente.setText("Gestion des ventes");
        jMenuItem_GestionVente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_GestionVenteActionPerformed(evt);
            }
        });
        jMenu1_Fenetre.add(jMenuItem_GestionVente);

        jMenuBar1.add(jMenu1_Fenetre);

        jMenu2_Edition.setText("Edition");
        jMenu2_Edition.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem_Copier.setText("Copier");
        jMenu2_Edition.add(jMenuItem_Copier);

        jMenuItem_Coller.setText("Coller");
        jMenu2_Edition.add(jMenuItem_Coller);

        jMenuItem_Couper.setText("Couper");
        jMenu2_Edition.add(jMenuItem_Couper);

        jMenuBar1.add(jMenu2_Edition);

        jMenu3_Aide.setText("Aide");
        jMenu3_Aide.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem_Apropos.setText("A_propos");
        jMenu3_Aide.add(jMenuItem_Apropos);

        jMenuBar1.add(jMenu3_Aide);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_GestionCltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_GestionCltActionPerformed
        // TODO add your handling code here:
        //Ouvrir la fenêtre client
        GestionClients clientFrame = new GestionClients();
        clientFrame.setVisible(true);
    }//GEN-LAST:event_jMenuItem_GestionCltActionPerformed

    private void jBtn_DeconnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DeconnecterActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, 
        "Voulez-vous vraiment vous déconnecter ?", 
        "Déconnexion", 
        JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose(); // Ferme la fenêtre actuelle
            try {
                new FenetreConnexion().setVisible(true); // Ouvre la fenêtre de connexion
            } catch (SQLException ex) {
                Logger.getLogger(FenetrePrincipale.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FenetrePrincipale.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBtn_DeconnecterActionPerformed

    private void jMenuItem_GestionUtiliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_GestionUtiliActionPerformed
         new GestionUtilisateurs().setVisible(true); // Ouvre la gestion des utilisateurs
    }//GEN-LAST:event_jMenuItem_GestionUtiliActionPerformed

    private void jMenuItem_GestionVenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_GestionVenteActionPerformed
        new GestionVente().setVisible(true); // Ouvre la gestion des ventes
    }//GEN-LAST:event_jMenuItem_GestionVenteActionPerformed

    private void jBtn_QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_QuitterActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Êtes-vous sûr de vouloir quitter ?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose(); // Ferme la fenêtre si l'utilisateur confirme
        }
    }//GEN-LAST:event_jBtn_QuitterActionPerformed

    private void jMenuItem_GestionParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_GestionParaActionPerformed
        // TODO add your handling code here:
        new GestionParametres().setVisible(true); // Ouvre la gestion des parametres
        
    }//GEN-LAST:event_jMenuItem_GestionParaActionPerformed

    private void jMenuItem_Gestion_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Gestion_stockActionPerformed
        new GestionDesStocks().setVisible(true); // Ouvre la gestion des stocks
    }//GEN-LAST:event_jMenuItem_Gestion_stockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Deconnecter;
    private javax.swing.JButton jBtn_Quitter;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1_Fenetre;
    private javax.swing.JMenu jMenu2_Edition;
    private javax.swing.JMenu jMenu3_Aide;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_Apropos;
    private javax.swing.JMenuItem jMenuItem_Coller;
    private javax.swing.JMenuItem jMenuItem_Copier;
    private javax.swing.JMenuItem jMenuItem_Couper;
    private javax.swing.JMenuItem jMenuItem_GestionClt;
    private javax.swing.JMenuItem jMenuItem_GestionPara;
    private javax.swing.JMenuItem jMenuItem_GestionUtili;
    private javax.swing.JMenuItem jMenuItem_GestionVente;
    private javax.swing.JMenuItem jMenuItem_Gestion_stock;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
