/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vue;

import Controle.Configuration;
import Modele.Parametres;
//import com.sun.jdi.connect.spi.Connection;
import javax.swing.JOptionPane;
import java.sql.Connection;

/**
 *
 * @author PC
 */
public class FenetreAdministration extends javax.swing.JFrame {

    /**
     * Creates new form FenetreParametres
     */
    public FenetreAdministration() {
        initComponents();
    }
    
    private void enregistrerParametres() {
        try {
            Configuration.setProperty("db.driver", jTextF_Driver.getText());
            Configuration.setProperty("db.url", jTextF_Url.getText());
            Configuration.setProperty("db.user", jTextF_User.getText());
            Configuration.setProperty("db.password", jPasswordF.getText());

            Configuration.saveAndEncryptProperties();

            JOptionPane.showMessageDialog(this, "✅ Paramètres enregistrés avec succès !");
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "❌ Erreur: " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLab_Titre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextF_User = new javax.swing.JTextField();
        jTextF_Driver = new javax.swing.JTextField();
        jPasswordF = new javax.swing.JPasswordField();
        jTextF_Url = new javax.swing.JTextField();
        jBtn_Enregistrer = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jBtn_Annuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLab_Titre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLab_Titre.setText("Fenetre de Configuration");
        getContentPane().add(jLab_Titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("User");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Driver");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Url");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jTextF_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextF_UserActionPerformed(evt);
            }
        });
        getContentPane().add(jTextF_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 350, -1));

        jTextF_Driver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextF_DriverActionPerformed(evt);
            }
        });
        getContentPane().add(jTextF_Driver, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 350, -1));

        jPasswordF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 350, -1));

        jTextF_Url.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextF_UrlActionPerformed(evt);
            }
        });
        getContentPane().add(jTextF_Url, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 350, -1));

        jBtn_Enregistrer.setBackground(new java.awt.Color(204, 204, 204));
        jBtn_Enregistrer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtn_Enregistrer.setText("Enregistrer");
        jBtn_Enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_EnregistrerActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn_Enregistrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/para.JPG"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 400));

        jPanel2.setBackground(java.awt.SystemColor.controlLtHighlight);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtn_Annuler.setBackground(new java.awt.Color(204, 204, 204));
        jBtn_Annuler.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtn_Annuler.setText("Annuler");
        jBtn_Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_AnnulerActionPerformed(evt);
            }
        });
        jPanel2.add(jBtn_Annuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 430, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextF_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextF_UserActionPerformed
        // TODO add your handling code here:
        Configuration.getProperty("db.user");
    }//GEN-LAST:event_jTextF_UserActionPerformed

    private void jTextF_DriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextF_DriverActionPerformed
        // TODO add your handling code here:
        Configuration.getProperty("db.driver");
    }//GEN-LAST:event_jTextF_DriverActionPerformed

    private void jPasswordFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFActionPerformed
        // TODO add your handling code here:
        Configuration.getProperty("db.password");
    }//GEN-LAST:event_jPasswordFActionPerformed

    private void jTextF_UrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextF_UrlActionPerformed
        // TODO add your handling code here:
        Configuration.getProperty("db.url");
    }//GEN-LAST:event_jTextF_UrlActionPerformed

    private void jBtn_EnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_EnregistrerActionPerformed
        // TODO add your handling code here:
        enregistrerParametres();
    }//GEN-LAST:event_jBtn_EnregistrerActionPerformed

    private void jBtn_AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_AnnulerActionPerformed
        // TODO add your handling code here:
        this.dispose();

        
    }//GEN-LAST:event_jBtn_AnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreAdministration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreAdministration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreAdministration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreAdministration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreAdministration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Annuler;
    private javax.swing.JButton jBtn_Enregistrer;
    private javax.swing.JLabel jLab_Titre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordF;
    private javax.swing.JTextField jTextF_Driver;
    private javax.swing.JTextField jTextF_Url;
    private javax.swing.JTextField jTextF_User;
    // End of variables declaration//GEN-END:variables
}
