/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vue;

import Controle.Configuration;
import Modele.Parametres;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class GestionParametres extends javax.swing.JFrame {

    /**
     * Creates new form GestionParametres
     */
    public GestionParametres() {
        initComponents();
    }
    
    private void afficherParametresBD() {
        try {
            String message = "📌 **Paramètres Actuels** :\n"
                    + "🔹 Driver : " + Configuration.getProperty("db.driver") + "\n"
                    + "🔹 URL : " + Configuration.getProperty("db.url") + "\n"
                    + "🔹 Utilisateur : " + Configuration.getProperty("db.user") + "\n"
                    + "🔹 Mot de passe : " + Configuration.getProperty("db.password") + "\n";

            JOptionPane.showMessageDialog(this, message, "Informations de Connexion", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "❌ Erreur : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBtn_ParamtresBD = new javax.swing.JButton();
        jBtn_AffichePara = new javax.swing.JButton();
        jBtn_Quitter = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fenetre D'administration");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jBtn_ParamtresBD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtn_ParamtresBD.setText("ParametresBD");
        jBtn_ParamtresBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ParamtresBDActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn_ParamtresBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jBtn_AffichePara.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtn_AffichePara.setText("AfficherParametres");
        jBtn_AffichePara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_AfficheParaActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn_AffichePara, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jBtn_Quitter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtn_Quitter.setText("Quitter");
        jBtn_Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_QuitterActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn_Quitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/image Admin.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 550, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_ParamtresBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ParamtresBDActionPerformed
        FenetreAdministration fenetreAdmin = new FenetreAdministration();
        fenetreAdmin.setVisible(true);
    }//GEN-LAST:event_jBtn_ParamtresBDActionPerformed

    private void jBtn_AfficheParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_AfficheParaActionPerformed
        // TODO add your handling code here:
        afficherParametresBD();
    }//GEN-LAST:event_jBtn_AfficheParaActionPerformed

    private void jBtn_QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_QuitterActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_jBtn_QuitterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionParametres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionParametres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionParametres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionParametres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionParametres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_AffichePara;
    private javax.swing.JButton jBtn_ParamtresBD;
    private javax.swing.JButton jBtn_Quitter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
